server:
  port: 8300
  servlet:
    session:
      timeout: 3600

spring:
  application:
    name: hzw-xyp-admin
  datasource:
    druid:
      url: jdbc:mysql://120.78.184.188:3306/hzw_xyp?useOldAliasMetadataBehavior=true&useSSL=false&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT%2B8
      username: root
      password: 
      initial-size: 1
      min-idle: 1
      max-active: 20
      test-on-borrow: true
      driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database: mysql
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  jta:
    transaction-manager-id: transactionManager
  ## 热部署
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
